spring:
  application:
    name: ttou-gayeon
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ttougayoen;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    hikari:
      maximum-pool-size: 4

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql